Repository jboss-container-images/rhdm-7-image, pull requests merged in 2020-11, with the labels that each got.

#394 Add Kaitou to default reviewers
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#403 [KIECLOUD-453] - Adapt product artifacts definitions to CPaaS build
  README.md
  controller/modules/controller/module.yaml
  decisioncentral/modules/decisioncentral/module.yaml
  kieserver/modules/kieserver/module.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#402 [KIECLOUD-453] - Adapt product artifacts definitions to CPaaS build
  README.md
  controller/modules/controller/module.yaml
  decisioncentral/modules/decisioncentral/module.yaml
  kieserver/modules/kieserver/module.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#413 [KIECLOUD-467] - Prepare RHDM and RHPAM 7.9.x branches for 7.9.1 release
  README.md
  controller/modules/controller/module.yaml
  decisioncentral/modules/decisioncentral/module.yaml
  kieserver/modules/kieserver/module.yaml
Labels: 7.9.x ⇨ 7.9.1, needs review :mag:
